---
# file: project/plantuml.yml

- hosts: plantuml
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/plantuml"
    - debug: var=fact_role_path

  roles:

    - plantuml
